import Head from "next/head";
import React from "react";
import sodium from "libsodium-wrappers";
import { useRouter } from "next/router";
import { v4 as uuidv4 } from "uuid";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Hello World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome</h1>
        <button
          onClick={() => {
            router.push(
              `/doc/${uuidv4()}#${sodium.to_base64(
                sodium.crypto_secretbox_keygen()
              )}`
            );
          }}
        >
          Create new Doc
        </button>
      </main>
    </>
  );
}
